# Generated by Django 3.2.12 on 2022-06-20 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Room',
            new_name='Notification',
        ),
    ]
