# Generated by Django 3.2.12 on 2022-06-20 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_name_notification_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-updates', '-created']},
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
