# Generated by Django 3.2.13 on 2022-06-22 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_rename_prn_profile_prn'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
